// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX0vZo2Uha0FDOOfWrawHHKARR28kiJlA',
    appId: '1:226581440325:web:c4025e74e678707112402c',
    messagingSenderId: '226581440325',
    projectId: 'flutterfire-plswork',
    authDomain: 'flutterfire-plswork.firebaseapp.com',
    storageBucket: 'flutterfire-plswork.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ5-E6yWMk_fCh9rxWfwnpofS2XhYwBT4',
    appId: '1:226581440325:android:d19d4eb5f8c6976c12402c',
    messagingSenderId: '226581440325',
    projectId: 'flutterfire-plswork',
    storageBucket: 'flutterfire-plswork.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6CHdf86z4U1O9MiScLY0aGuSb2tl2DzU',
    appId: '1:226581440325:ios:ee23251439367ae412402c',
    messagingSenderId: '226581440325',
    projectId: 'flutterfire-plswork',
    storageBucket: 'flutterfire-plswork.appspot.com',
    iosClientId: '226581440325-8h8spg8kffl63r5e9ncvdnl48uot0ukg.apps.googleusercontent.com',
    iosBundleId: 'com.example.teste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6CHdf86z4U1O9MiScLY0aGuSb2tl2DzU',
    appId: '1:226581440325:ios:ee23251439367ae412402c',
    messagingSenderId: '226581440325',
    projectId: 'flutterfire-plswork',
    storageBucket: 'flutterfire-plswork.appspot.com',
    iosClientId: '226581440325-8h8spg8kffl63r5e9ncvdnl48uot0ukg.apps.googleusercontent.com',
    iosBundleId: 'com.example.teste',
  );
}
